services:
  # See tools/init-setup-nextcloud.sh for first install
  nextcloud:
    depends_on:
      - mariadb
    image: linuxserver/nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - confignextcloud:/config
      - nextclouddata:/data
      - torrents:/torrents
      - config:/seedbox-config

volumes:
  confignextcloud:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud
  nextclouddata:
    driver: local-persist
    driver_opts:
      mountpoint: $HOST_CONFIG_PATH/nextcloud-data